version: '3'

services:

  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_SECRET}
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: ${PRISMA_CONNECTOR}
            host: ${MYSQL_HOST}
            port: ${MYSQL_PORT}
            user: ${MYSQL_ROOT_USER}
            password: ${MYSQL_ROOT_USER}

  prisma-db:
    image: mysql:5.7
    container_name: prisma-db
    restart: always
    env_file:
      - ./.env
    volumes:
      - mysql/data:/var/lib/mysql